on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          path: nix-dms-plugins
      - uses: actions/checkout@v5
        with:
          repository: "AvengeMedia/dms-plugin-registry"
          path: dms-plugin-registry
      - name: Generate plugin data
        run: |
          PLUGINS_PREFETCH="$(pwd)/nix-dms-plugins/plugins-prefetch.json"
          echo "{" > "$PLUGINS_PREFETCH"
          cd dms-plugin-registry/plugins
          for plugin in *; do
              echo "\"$(jq -r '.id' $plugin)\":" >> "$PLUGINS_PREFETCH"
              nix shell nixpkgs#nix-prefetch-git \
                --command nix-prefetch-git "$(jq -r '.repo' $plugin)" \
                | jq --slurpfile meta "$plugin" '.meta = $meta[0]' \
                >> "$PLUGINS_PREFETCH"
                echo "," >> "$PLUGINS_PREFETCH"
          done
          # Remove last comma
          sed -i '$ d' "$PLUGINS_PREFETCH"
          echo "}" >> "$PLUGINS_PREFETCH"
          TMP="$(mktemp)"
          mv "$PLUGINS_PREFETCH" "$TMP"
          jq . "$TMP" > "$PLUGINS_PREFETCH"
      # - name: Check plugins
      #   run: nix flake check ./nix-dms-plugins
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update plugin data
          repository: nix-dms-plugins
